### ISSUE TITLE
FeatureRequest: GreatorOrEqualThan & SmallerOrEqualThan

### ISSUE THREAD

**Issue by eugeneugene** [TanvirArjel/AspNetCore.CustomValidation#1]
Hi! Nice job!
It would be even better if you could also implement GreaterOrEqualThan and SmallerOrEqualThan comparison types

**Comment by TanvirArjel** [comment]
@eugeneugene Surely I am going to implement your requested features. It would be great if you star the repository please!

**Comment by TanvirArjel** [comment]
@eugeneugene Your requested features are now available in version `1.4.0`. Please try it out and let me know you have any further issue.
