### ISSUE TITLE
FeatureRequest: CompareTo attribute - compare Timespan

### ISSUE THREAD

**Issue by ExLuzZziVo** [TanvirArjel/AspNetCore.CustomValidation#3]
Hi, can you please add support for comparison of Timespan in CompareTo attribute?

**Comment by TanvirArjel** [comment]
@ExLuzZziVo Thank you for asking this feature. Surely I shall take a look onto it and also your pull request.

**Comment by TanvirArjel** [comment]
@ExLuzZziVo Hi, version [1.5.0](https://www.nuget.org/packages/AspNetCore.CustomValidation) has been published in nuget which includes your requested feature. Please try it out and let me know if there are any further issues.

Thank you.

Note: Please don't forget to star the repository. 😊
