### ISSUE TITLE
Bug: Localized error messages don't work in CompareTo Attribute

### ISSUE THREAD

**Issue by ExLuzZziVo** [TanvirArjel/AspNetCore.CustomValidation#5]
Localized error messages don't work in CompareTo Attribute because **ErrorMessage** is used instead of **ErrorMessageString** in lines like:

`
private string EqualityErrorMessage => ErrorMessage ?? "The {0} is not equal to {1}.";
`

If ErrorMessageResourceType and ErrorMessageResourceName are set, then ErrorMessage is always null.

If I change **ErrorMessage** to **ErrorMessageString** everything works as expected.

**Comment by TanvirArjel** [comment]
@ExLuzZziVo Thank you for submitting the issue. Surely I shall take a look onto it.

**Comment by TanvirArjel** [comment]
@ExLuzZziVo This issue has been fixed. Now from **version 2.0.0** `AspNetCore.CustomValidation` has fullfledged localization support for all the error messages. Please check.
